apiVersion: v2
name: spotify-reblend
description: A Helm chart for Spotify ReBlend application
type: application
sources:
  - https://github.com/Soli0222/spotify-reblend
version: 0.5.0
appVersion: "1.5.0"
